sensics/OSVR-RenderManager

osvr/RenderKit/RenderManager.h, osvr/RenderKit/RenderManagerBase.cpp
None is a reserved keyword in X11.
=> RenderManager: Replace None by Zero.

CMakeLists.txt, cmake/FindOpenGLES2.cmake, examples/CMakeLists.txt, examples/RenderManagerOpenGLES2Example.cpp, osvr/RenderKit/RenderManagerBase.cpp, osvr/RenderKit/RenderManagerOpenGL.h
Also compiles and links on Android using OSVR-Android-Build project.  Not yet tested.  Includes an example GLES application.
=> Merge android

examples/AdjustableRenderingDelayD3D.cpp, examples/AdjustableRenderingDelayOpenGL.cpp, examples/RenderManagerD3DATWDoubleBufferExample.cpp, examples/RenderManagerD3DExample3D.cpp, examples/RenderManagerD3DHeadSpaceExample.cpp, examples/RenderManagerD3DPresentExample3D.cpp, examples/RenderManagerD3DPresentMakeDeviceExample3D.cpp, examples/RenderManagerD3DPresentSideBySideExample.cpp, examples/RenderManagerD3DTest2D.cpp, examples/RenderManagerOpenGLCoreExample.cpp, osvr/RenderKit/RenderManagerD3DBase.cpp, osvr/RenderKit/RenderManagerOpenGL.cpp
This fixes the missing antialiasing in Direct3D rendering and makes black borders rather than clamped textures for both OpenGL and Direct3D.
=> Borders and blurring

osvr/RenderKit/RenderManagerBase.cpp
Actually adjusted the creation and destruction of client contexts and turned off disabling of DirectMode when the config file changes things.
=> Atw bug fixing

osvr/RenderKit/RenderManagerD3D11ATW.h, osvr/RenderKit/RenderManagerD3DOpenGL.cpp
Should improve tearing on ATW and OpenGL/DirectMode.
=> Wait for render completion

osvr/RenderKit/RenderManagerD3DBase.cpp
...to support additional color buffer formats.
=> Modified osvr::renderkit::RenderManagerD3D11Base::PresentEye... 

CMakeLists.txt, RenderManagerBackends.h.in, examples/RenderManagerOpenGLQt5Example.cpp, examples/RenderManagerOpenGLSharedContextExample.cpp, osvr/RenderKit/GraphicsLibraryOpenGL.h, osvr/RenderKit/RenderManagerBase.cpp, osvr/RenderKit/RenderManagerOpenGL.cpp, osvr/RenderKit/RenderManagerOpenGL.h, osvr/RenderKit/RenderManagerOpenGLC.h, osvr/RenderKit/RenderManagerOpenGLVersion.h, tests/header_dependencies/CMakeLists.txt
A number of fixes, including making a common header file for OpenGL for all architectures (it decides internally whether to use OpenGL or OpenGLES.
=> Common header files for opengl

examples/RenderManagerOpenGLQt5Example.cpp, osvr/RenderKit/RenderManagerOpenGL.cpp, osvr/RenderKit/RenderManagerOpenGLC.h
Implements: https://github.com/sensics/OSVR-RenderManager/issues/154
=> Added new getDisplayFrameBuffer callback to OSVR_OpenGLToolkitFunctions

osvr/RenderKit/RenderManagerOpenGL.cpp
This fixes issue https://github.com/sensics/OSVR-RenderManager/issues/208
=> Vao restore

CMakeLists.txt, osvr/RenderKit/RenderManagerOpenGL.cpp, osvr/RenderKit/RenderManagerOpenGLC.cpp
A few changes and fixes for building and running on Android.
=> Android fixes

osvr/RenderKit/RenderManagerOpenGL.cpp
=> Fixed typo

osvr/RenderKit/RenderManagerBase.cpp
Uses a submodule version that implements this.
=> Constructing the D3D11 device in one step.

osvr/RenderKit/RenderManagerD3DBase.cpp
Broke my own rule about not "fixing" code that is already working.
Fixes Unity, and probably also Unreal bug introduced Dec 26, 2016.
=> Reverts an earlier commit that breaks rendering for typeless textures.

CMakeLists.txt, apps/CMakeLists.txt, apps/RenderManagerOpenGLChessboard.cpp
Modified version of the High Poly example, that just displays what should ideally be a full-viewport black and white chessboard.
=> Add OpenGL chessboard

osvr/RenderKit/RenderManagerD3D11ATW.h
Solves https://github.com/sensics/OSVR-RenderManager/issues/64
=> Atw improvements

examples/RenderManagerOpenGLCAPIExample.cpp
Fixed a GL_ERROR in the CAPIExample, which was binding the colour buffer in a different way to how RenderManagerOpenGL was doing this.
Replaced calls & types from the C++ api with C api equivalents.
=> Fixed GL error in RenderManagerOpenGLCAPIExample, and made it use the C API exclusively

examples/RenderManagerD3DExample3D.cpp, osvr/RenderKit/RenderManagerBase.cpp, osvr/RenderKit/RenderManagerD3D.cpp, osvr/RenderKit/RenderManagerD3D.h, osvr/RenderKit/RenderManagerOpenGL.cpp
This handles the issues fixed in https://github.com/sensics/OSVR-RenderManager/pull/339 along with some other ones.  It works in concert with the three submodule pull requests made on the AMD, NVIDIA, and Intel modules.
=> Fix render timing info

osvr/RenderKit/DirectModeVendors.h
- Added new TotalVision Vendor ID 'TVL'
- Added description.
Please merge )
Thank you!
=> Added new TotalVision's VendorID

osvr/RenderKit/DirectModeVendors.h
Added a new Vendor ID 'NEC' advertised by Lumus' dev kit.
Please merge! Thanks :)
=> Added a new Vendor ID

osvr/RenderKit/RenderManager.h, osvr/RenderKit/RenderManagerC.cpp, osvr/RenderKit/RenderManagerC.h, osvr/RenderKit/RenderManagerImpl.h, osvr/RenderKit/osvr_display_configuration.cpp, osvr/RenderKit/osvr_display_configuration.h
Resolves issue https://github.com/sensics/OSVR-RenderManager/issues/293
=> Read params from display config
