examples/CMakeLists.txt

This applies the same trick used to compile the RenderManager library to the examples.

examples: Target the C++11 compiler for all executables.

---

README.md
vendor/CMakeLists.txt

Fixes things so that you can get VRPN without its submodules and build even if you don't have access to the NDA repositories.  Also adds build instructions for folks who can't read the NDA repos.

Build and doc fixes

---

examples/AdjustableRenderingDelayD3D.cpp
osvr/RenderKit/RenderManager.h
osvr/RenderKit/RenderManagerBase.cpp

Adds client-side prediction.  Works with the DK2, but currently fails with HDK because the transform tree doesn't yet know how to handle adjusting velocities.  Does no harm because it needs to be explicitly turned on in the config file.

Client side prediction

---

examples/LatencyTestD3DExample.cpp
osvr/RenderKit/RenderManager.h
osvr/RenderKit/RenderManagerD3D.cpp
osvr/RenderKit/RenderManagerD3D11ATW.h
osvr/RenderKit/RenderManagerD3D11C.cpp
osvr/RenderKit/RenderManagerD3D11C.h
osvr/RenderKit/RenderManagerD3DBase.cpp
osvr/RenderKit/RenderManagerD3DBase.h
osvr/RenderKit/RenderManagerD3DOpenGL.cpp
osvr/RenderKit/RenderManagerImpl.h
osvr/RenderKit/RenderManagerOpenGL.cpp
osvr/RenderKit/RenderManagerOpenGLC.cpp

Fixes issues with multi-GPU under D3D11 and crashes when NULL device and contexts are passed in using the C API.
Also removes structures from the OpenDisplay return structure that are not needed; this "fixes" problems when client programs expect them to be filled in with something useful and they are not.  This was a holdover from an earlier implementation.
The last change modifies client-facing structures in the C++ and C APIs.

Fixing d3d issues

---

osvr/RenderKit/RenderManagerOpenGL.cpp

```
RenderManagerOpenGL::OpenDisplay: Could not construct vertex shader
```
is not the best error message, when OpenGL can tell us what's wrong. For example this is the output with mesa drivers with the OpenGL Compatibility profile (mesa drivers only support GLSL 310+ with the Core profile):
```
RenderManagerOpenGL::OpenDisplay: Could not construct vertex shader:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES
```

InfoLog output on distortion shader compile error

---

examples/AdjustableRenderingDelayD3D.cpp
examples/AdjustableRenderingDelayOpenGL.cpp
examples/CMakeLists.txt
examples/LatencyTestD3DExample.cpp
examples/RenderManagerD3DATWDoubleBufferExample.cpp
examples/RenderManagerD3DExample3D.cpp
examples/RenderManagerD3DHeadSpaceExample.cpp
examples/RenderManagerD3DPresentExample3D.cpp
examples/RenderManagerD3DPresentMakeDeviceExample3D.cpp
examples/RenderManagerD3DPresentSideBySideExample.cpp
examples/RenderManagerD3DTest2D.cpp
examples/RenderManagerOpenGLCoreExample.cpp
examples/RenderManagerOpenGLExample.cpp
examples/RenderManagerOpenGLHeadSpaceExample.cpp
examples/RenderManagerOpenGLPresentExample.cpp
examples/RenderManagerOpenGLPresentSideBySideExample.cpp
examples/RenderManagerOpenGLSharedContextExample.cpp
examples/SpinCubeD3D.cpp
examples/SpinCubeOpenGL.cpp
installer/directmode_HDK1.3_ATW.json
installer/osvrRenderManager.aip
osvr/RenderKit/GraphicsLibraryD3D11.h
osvr/RenderKit/GraphicsLibraryOpenGL.h
osvr/RenderKit/RenderKitGraphicsTransforms.cpp
osvr/RenderKit/RenderKitGraphicsTransforms.h
osvr/RenderKit/RenderManager.h
osvr/RenderKit/RenderManagerBase.cpp
osvr/RenderKit/RenderManagerD3DOpenGL.cpp
osvr/RenderKit/RenderManagerOpenGL.cpp

This has modifications to the OpenGL DirectMode code and to the base class, adding a flag to tell OpenGL to share contexts with the main app.  Added an example program that runs in both windowed and DirectMode cases.  Not yet tested with an app that uses other than SDL to construct its context.

Opengl sharing

---

CMakeLists.txt
examples/CMakeLists.txt
examples/RenderManagerOpenGLSharedContextExample.cpp
examples/RestartD3D.cpp
osvr/RenderKit/RenderManagerBase.cpp
osvr/RenderKit/RenderManagerD3D.cpp
osvr/RenderKit/RenderManagerOpenGL.cpp
osvr/RenderKit/RenderManagerOpenGL.h
osvr/RenderKit/RenderManagerSDLInitQuit.cpp
osvr/RenderKit/RenderManagerSDLInitQuit.h

This makes SDL_Init() be called only once and prevents SDL_Quit() from being called during RenderManager destruction.  This enables an app to delete and then recreate a RenderManager while running.  Included new test app that deletes and makes new RenderManagers to make sure this is working.

Support restart

---

osvr/RenderKit/RenderManagerC.cpp
osvr/RenderKit/RenderManagerC.h
osvr/RenderKit/RenderManagerD3D11C.cpp
osvr/RenderKit/RenderManagerD3D11C.h
osvr/RenderKit/RenderManagerImpl.h
osvr/RenderKit/RenderManagerOpenGLC.cpp
osvr/RenderKit/RenderManagerOpenGLC.h

This adds a new C API for getting an `OSVR_RenderInfoCollection` (an opaque type) atomically. This replaces the old API for getting render info, which got the render info collection again every time a given render info was accessed. The old API is still available but marked deprecated.

Render info c api update

---

osvr/RenderKit/osvr_display_configuration.cpp

These are a collection of improvements to the distortion parsing code.
- some small performance improvements:
- avoiding deep-copying `Json::Value` when we can take a `const &`
- only doing things like `Json::Value::toString()` once and saving the result, instead of doing it repeatedly thus converting, creating, and destroying string objects over and over.
- Passed `false` as the third, optional parameter to the `Json::Reader::parse()` method - `bool collectComments` - since we're not manipulating the json file for general usage and output, we just want the data, so we can tell the parser to totally ignore comments.
- some de-duplication in the loading of external files: it didn't quite meet the general "rule of 3" (generalize code if it will be used 3 times) because it was used only …

Distortion parsing improvements

---

osvr/RenderKit/RenderManagerBase.cpp

A comment somewhere mentioned wanting to know how to avoid needing to memcpy, and it is in fact possible in nearly all cases, using the `Map` class: the full gory details on how to use persistent variables of `Map<>` type are here https://eigen.tuxfamily.org/dox/group__TutorialMapClass.html However, that's more complex than you typically need to do:  I tend to use it more as in this patch, using the static members of the various vector and matrix types to make a (optimized away) temporary map for assignment or input purposes: note that it can be used on either side of an expression (as input or as a destination for assignment).
These should get you most everywhere you want to go:
- `Eigen::Vector2d::Map(double* or double const *)`
- `Eigen::Vector3d::Map(double* or double const *)`
- …

Use Eigen::Map facility to avoid a use of memcpy.

---

osvr/RenderKit/RenderManagerBase.cpp

VRGate have been signed the NDA with OSVR recently, here is the vendor name to PnP-id mapping of our HMD.

Adding VRGate HMD to list of DirectMode displays.

---

CMakeLists.txt
osvr/RenderKit/RenderManagerOpenGLC.h
tests/CMakeLists.txt
tests/header_dependencies/CMakeLists.txt
tests/header_dependencies/main.c
tests/header_dependencies/main.cpp

If `BUILD_TESTS` is enabled in CMake, this will run the same header-dependency tests that we use in OSVR-Core. Each test includes a single header file and builds a no-op program. If the program builds successfully, it means the header includes (directly or indirectly) all its dependencies. If it fails to build, it may be missing a dependency, or have some other program (check the compiler output for details).
Headers from submodules have not been tested yet, so you may encounter errors when building those. If they require libraries or should be ignored entirely, edit the `tests/header_dependencies/CMakeLists.txt` file appropriately.

Add header-dependency tests

---

osvr/RenderKit/RenderManagerImpl.h

renderInfoIndex is unsigned, therefore always > 0.

Fixes a tautological warning

---

osvr/RenderKit/RenderManagerBase.cpp

Unfortunately our newer vendor id 'VRG' has not been
approved by Microsoft yet, this will lead to problems
on AMD cards (drivers), so we need a fallback for now.

Added another PnP vendor id for VRGate HMD.

---

examples/RenderManagerOpenGLQt5Example.cpp
osvr/RenderKit/RenderManagerOpenGL.cpp
osvr/RenderKit/RenderManagerOpenGLC.h

In OSVR-Unreal, we need an override to change the display size, because of mobile scaling. The actual display size may end up being smaller than the physical resolution. This new callback allows a custom toolkit to override the display size.
Implements: https://github.com/sensics/OSVR-RenderManager/issues/161

Added getDisplaySizeOverride callback to OSVR_OpenGLToolkitFunctions

---

osvr/RenderKit/RenderManagerBase.cpp

fixes
```
/home/chris/build/osvr-rendermanager/src/osvr-rendermanager/osvr/RenderKit/RenderManagerBase.cpp: In member function 'virtual bool osvr::renderkit::RenderManager::PresentRenderBuffersInternal(const std::vector<osvr::renderkit::RenderBuffer>&, const std::vector<osvr::renderkit::RenderInfo>&, const osvr::renderkit::RenderManager::RenderParams&, const std::vector<osvr::renderkit::OSVR_ViewportDescription>&, bool)':
/home/chris/build/osvr-rendermanager/src/osvr-rendermanager/osvr/RenderKit/RenderManagerBase.cpp:726:45: error: 'vrpn_gettimeofday' was not declared in this scope
vrpn_gettimeofday(&allStart, nullptr);
^
/home/chris/build/osvr-rendermanager/src/osvr-rendermanager/osvr/RenderKit/RenderManagerBase.cpp:749:77: error: 'vrpn_TimevalDurationSeconds' was not declared in this …
```

include "vrpn_Shared.h"

---

CMakeLists.txt
osvr/RenderKit/CleanPNPIDString.h
osvr/RenderKit/DirectModeVendors.h
osvr/RenderKit/RenderManagerBase.cpp

This is a refactoring that pulls the association of PNPID with device descriptor vendor name and a "human readable" string (like "most OSVR HDK devices") out of a massive if-else in RenderManagerBase  (and in part, the enable/disable direct mode tools) and into a data structure (static, in a header, so the direct mode enable/disable still won't need to link against rendermanager to use it).
This is the first part of the de-duplication of this data - pull requests on the submodules will come as well, so this new header will be the single source of truth for hard-coded PNPIDs.
This also contains support for "testing" or otherwise custom PNPIDs - if a vendor name is not found in the list, but take the form of 3 characters in `[A-Z]`, it will be added as a candidate pnpid, allowing testing …

Factor out vendors

---

osvr/RenderKit/DirectModeVendors.h
osvr/RenderKit/VendorIdTools.h

This should fix the build on GCC 4.9 - apparently my previous syntax was technically legal (maybe) but the new syntax is more legal and more simple. Also more commented.
cc @JeroMiya

Vendor initializers

---

CMakeLists.txt
osvr/RenderKit/DirectModeToolSkeleton.h
osvr/RenderKit/DirectModeVendors.h
osvr/RenderKit/RenderManagerBase.cpp
osvr/RenderKit/ToolingArguments.h
tests/header_dependencies/CMakeLists.txt

This encompasses pull requests in the NDA submodules as well as some changes in the main repo, generally to simplify and standardize handling of the list of vendor IDs that might be involved in direct mode. It is a logical continuation of an earlier pull that made the vendor ID list into a header of its own.
There are now two vendor ID lists - one contains vendor IDs we'll investigate to see if they're in direct mode, but won't automatically put in direct mode. Samsung was moved to this list, so that we don't automatically put any samsung regular monitors into direct mode, e.g. on AMD where product-specific whitelisting by the driver isn't required.
DirectModeDebugging (for NVIDIA) now also uses this list, and can take command line args - try `-h`. 
Both the AMD and NVIDIA direct mode …

Simplify enable disable

---

CMakeLists.txt

Links against display server client static library if available, avoiding need to preload another DLL.

Build against static library if available.

---

osvr/RenderKit/DirectModeVendors.h

Adds the FOVE HMD display to the list of direct mode vendors per the documentation at:
https://github.com/OSVR/OSVR-Docs/blob/master/Extending-OSVR/AddingHMD.md

Add FOVE PNP ID to direct mode vendor list

---

osvr/RenderKit/osvr_display_configuration.cpp

For some unknown reason I needed to remove `operator=` calls in this function or it wouldn't link, when using JsonCpp-0yz and VS2015 64 bit. It's effectively equivalent (pass an arg by value instead of passing by const ref then assigning to a new object, and a swap instead of an assign), and importantly, it builds.

Adjust mesh parsing to avoid strange linker error with Json assignment operator.

---

CMakeLists.txt
osvr/RenderKit/DeltaQuatDeadReckoning.h
osvr/RenderKit/PoseStateCaching.h
osvr/RenderKit/RenderManager.h
osvr/RenderKit/RenderManagerBase.cpp
tests/header_dependencies/CMakeLists.txt

This improves the method for obtaining pose state and reliably predicting pose ahead to a given point in time, in part by making the code paths equivalent regardless of whether you have the timestamp override turned on or not.  Code I had worked on a while ago, just hadn't submitted it for PR despite using it locally.

Stabilize timing

---

CMakeLists.txt

Was missing OpenGL and D3D C++ header files.  Added them to so that the osvr::RenderKit::RenderManager can be static_casted into the underlying type, if it's known in advance.
Covers issue #329

Added missing public header files to the CMakeLists.txt

---

osvr/RenderKit/RenderManagerBase.cpp
osvr/RenderKit/RenderManagerOpenGL.h

Fixes [this compiler error](https://github.com/sensics/OSVR-RenderManager/pull/330#issuecomment-320381229) by providing a dummy `RenderManagerD3D11Base` class for non-D3D systems.

Linux and macOS tweaks

---

.gitignore
examples/RenderManagerOpenGLQt5Example.cpp
osvr/RenderKit/RenderManager.h
osvr/RenderKit/RenderManagerBase.cpp
osvr/RenderKit/RenderManagerC.h
osvr/RenderKit/RenderManagerD3D11ATW.h
osvr/RenderKit/RenderManagerD3DOpenGL.h
osvr/RenderKit/RenderManagerOpenGL.cpp
osvr/RenderKit/RenderManagerOpenGL.h
osvr/RenderKit/RenderManagerOpenGLC.h

Adds an override to the OpenGL toolkit structure that allows applications to provide custom vsync timing information to RenderManager from a custom OpenGL window toolkit implementation (example SDL, Android View, Qt, etc...). No implementation is given for existing implementations - currently the SDL implementation which is the default on non-Android platforms, and the sample Qt implementation.

Custom gl timing info

---

CMakeLists.txt

This was @russell-taylor 's work I just saw on gitk - is this ready to merge? Is it possibly related to https://github.com/OSVR/OSVR-Core/issues/562 ?

Fix infinite loop

---

CMakeLists.txt

This fixes the CI builds. Presumably https://github.com/OSVR/OSVR-Core/issues/568 combined with matching boost versions on the various CI builders was somehow masking this issue earlier.

Explicitly include boost in the NDA projects.

---

osvr/RenderKit/RenderManagerOpenGL.cpp
osvr/RenderKit/RenderManagerOpenGL.h

Not sure how this was building before on Android, but it didn't build with a newer NDK 16b-based setup (using clang and libc++).  Pretty clear duplicated definition, fairly straightforward resolution. File statics are guaranteed to be initialized by the time any code later in the file/TU is run, IIRC, so this should be the safe solution.

Fix multiple definition of function pointers in OpenGL ES (Android)

---

osvr/RenderKit/RenderManager.h
osvr/RenderKit/RenderManagerBase.cpp

If left and right viewpoint poses are present (we are getting reports from /me/viewpoints/left and /me/viewpoints/right), use them in ConstructModelView instead of head pose +- ipd
Continued from https://github.com/sensics/OSVR-RenderManager/pull/345

Uses /me/viewpoints/left and /me/viewpoints/right poses in ConstructModelView

---

osvr/RenderKit/DirectModeVendors.h
osvr/RenderKit/RenderManagerOpenGL.cpp
osvr/RenderKit/RenderManagerOpenGL.h

Fixed a bug found when looking into compiler complaints.  Turns out we were setting the framebuffer in ways that often happen not to break things but are not correct for the OpenGL rendering path.

Fix framebuffer bug
